# Generated by Django 4.0.6 on 2022-08-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_remove_user_id_remove_user_name_user_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
