# Generated by Django 4.0.6 on 2022-08-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(default='', max_length=255, verbose_name='NomProd')),
                ('categoria_producto', models.CharField(default='', max_length=255, verbose_name='Categoria')),
                ('cant_disponible', models.BigIntegerField(default=1)),
            ],
        ),
    ]
